#!/usr/bin/env python3

import json
from urllib import request
from urllib.error import HTTPError


WEBHOOK_URL = 'https://discordapp.com/api/webhooks/xxx/yyy'

payload = {
    'content': "Nouveautés",
    'embeds': [
        {
            'title': 'Nintendo',
            'description': 'Dernières actualités',  # Le corps de la carte
            'url': 'https://www.instagram.com/nintendo/',
        },
    ]
}

# Les paramètres d'en-tête de la requête
headers = {
    'Content-Type': 'application/json',
    'user-agent': 'Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11'
}

# Enfin on construit notre requête
req = request.Request(url=https://discord.com/api/webhooks/815953990781108254/3hm7K7176HSda2eB_yOcROSFJ02-FKsj5ovNQfjOrl58ZQxc1W86Axxcb80InnhsyWPWL,
                      data=json.dumps(payload).encode('utf-8'),
                      headers=headers,
                      method='POST')

# Puis on l'émet !
try:
    response = request.urlopen(req)
    print(response.status)
    print(response.reason)
    print(response.headers)
except HTTPError as e:
    print('ERROR')
    print(e.reason)
    print(e.hdrs)
    print(e.file.read())
